import { fontSans } from '@/config'
import { Providers } from '@/providers'
import type { Metadata } from 'next'
import { Toaster } from 'sonner'

import '../src/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="es"
      suppressHydrationWarning
    >
      <body
        className={`${fontSans.className} selection:bg-black selection:dark:bg-white selection:text-white selection:dark:text-black`}
      >
        <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
